### ISSUE TITLE
Error: "The DateTime represented by the string '1397-04-31T00:51:37Z' is not supported in calendar "

### ISSUE THREAD

**Issue by it19862** [miladsoft/npoi#1]
**Logics:**
-. Copy the file "demo.xlsx"
     from the folder .. \ npoi_Example\wwwroot\demo.xlsx;
     to c:\test\visualStudio\demo.xlsx folder.
-. Launched a program;
-. The browser has opened;
-. The user selects the file - "c:\test\visualStudio\ demo.xlsx";
-. The user clicks the "Select File" button;
-. The user selects a file;
-. The user clicks the "Upload" button.
-. Result: error.
Error:
_The DateTime represented by the string '1397-04-31T00:51:37Z' is not supported in calendar_

![2020-03-01_21-23-18](https://user-images.githubusercontent.com/18245828/75631621-7540e300-5c05-11ea-9e3b-00131fa7b2eb.png)
![2020-03-01_20-59-38](https://user-images.githubusercontent.com/18245828/75631622-770aa680-5c05-11ea-92dd-ab08698e1a24.png)

**Comment by miladsoft** [comment]
You must first convert the text date to date format
