### ISSUE TITLE
Where is the "Выберите файл" button?

### ISSUE THREAD

**Issue by it19862** [miladsoft/npoi#2]
Where is the “Файл не выбран” message?
 
I can not find it in the file "Index.cshtml"

![2020-03-01_21-23-18](https://user-images.githubusercontent.com/18245828/75631707-3cedd480-5c06-11ea-8027-0c93eb0f8488.png)

**Comment by miladsoft** [comment]
you can use [Custom File Input Styling](https://codepen.io/wizardofcodez/pen/XWddObO) for change text of message !
